### ISSUE TITLE
Declaration error

### ISSUE THREAD

**Issue by pahom-berdyansk** [kevinkhill/Codeigniter-gCharts#1]
A PHP Error was encountered

Severity: Runtime Notice

Message: Declaration of colorAxis::values() should be compatible with configOptions::values()

Filename: configs/colorAxis.php

Line Number: 0

Backtrace:

File: /home/azov/php/test.ru/application/libraries/Gcharts.php
Line: 257
Function: _error_handler

File: /home/azov/php/test.ru/application/libraries/Gcharts.php
Line: 257
Function: __construct

File: /home/azov/php/test.ru/application/controllers/user/Mainpage.php
Line: 8
Function: __construct

File: /home/azov/php/test.ru/index.php
Line: 292
Function: require_once

How to fix this problem? Thanks

**Comment by kevinkhill** [comment]
I no longer maintain this library, please use the active fork of this, [Lavacharts](lavacharts.com)
